### ISSUE TITLE
Code Sniffer asks for a @return tag while the method doesnt return anything

### ISSUE THREAD

**Issue by Oliboy50** [M6Web/Symfony2-coding-standard#14]
Consider the following snippet:
```
    /**
     * @param array $c
     */
    protected function parseClipData(array &$c)
    {
        usort($c, function ($a, $b) {
            return strtotime($b) - strtotime($a);
        });
    }
```
Coding standard should be OK with this.

But here is its output:
```
ERROR | Missing @return tag in function comment
```

Because it sees the `return` statement in the closure, it requires us to add a `@return` phpDoc tag in our function like the following, even if the function does not return anything:
```
    /**
     * @param array $c
     *
     * @return void
     */
    protected function parseClipData(array &$c)
    {
        usort($c, function ($a, $b) {
            return strtotime($b) - strtotime($a);
        });
    }
```

**Comment by b-viguier** [comment]
Should be fixed in this file https://github.com/M6Web/Symfony2-coding-standard/blob/master/Symfony2/Sniffs/Commenting/FunctionCommentSniff.php

**Comment by cedvan** [comment]
:+1:

**Comment by jdlabails** [comment]
correct by v3.3.0
