### ISSUE TITLE
Liste des règles spécifiques

### ISSUE THREAD

**Issue by KuiKui** [M6Web/Symfony2-coding-standard#16]
Serait-il possible d'avoir une liste des règles ajoutées ou supprimées par rapport aux standards stricts de Symfony, dans le README ?

**Comment by mikaelrandy** [comment]
Oui, on pourrait mais le standard M6Web_symfony2 est justement la surcouche qui diffère du standard.

Ceci dit, ça fait un moment que je n'ai plus comparé avec le repo officiel

**Comment by KuiKui** [comment]
Oui, c'est justement pour ça qu'avoir la liste des différences serait intéressant 😉 
Pour savoir ce qu'on gagne et ce qu'on perd à utiliser le standard de M6.
