### ISSUE TITLE
Future of param & return docblocks with PHP7

### ISSUE THREAD

**Issue by tristanbes** [M6Web/Symfony2-coding-standard#19]
Hey,

On PHP5 we had : 

```php
    /**
     * @param Request $request
     *
     * @Route("/queue/wanna-speak/process", name="ws_queue")
     * @Method({"GET"})
     *
     * @return Response
     */
    public function queueAction(Request $request)
    {
        return new Response();
    }
```

on PHP7 we can simplify this by using:

```php
    /**
     * @Route("/queue/wanna-speak/process", name="ws_queue")
     * @Method({"GET"})
     */
    public function queueAction(Request $request): Response
    {
        return new Response();
    }
```

Since we can take advantage on **advanced type hinting** AND **return types**, the functions/methods can now contains everything we need (parameters & returns) to *not* write the `@param` and `@return` docblock

What do you think of dropping those rules ?

**Comment by dantleech** [comment]
I am currently dropping them, but the type hints do not cover all scenarios - e.g. mixed types and objects? possility of returning a NULL value?

```
/**
 * @param object $foo
 * @param int|string $bar
 *
 * @return string|null
 */
public function doSomething($foo, $bar)
```

So maybe just add them when something is not clear.

**Comment by ciaranmcnulty** [comment]
Where the language conveys the same information as the docblock, drop it

**Comment by QuingKhaos** [comment]
Sadly PhpStorm doesn't use type-hints for viewing usefull doc blocks..

**Comment by tristanbes** [comment]
@dantleech returning null values is covered by `PHP7.1` [source](https://blog.pascal-martin.fr/post/php71-en-types.html)

``` php
function returns_nothing(): void
{
    // This function returns null
    return;
}

function does_not_return(): void
{
    // This function returns null too
}
```

When something is not covered I do agree, we can add them the "old way", but no longer trigger a CS violation for not writing redundant information on 99% of cases.

**Comment by dantleech** [comment]
@tristanbes thanks, also nullable type declarations: `function fonc02(?int $a, ?int $b) : ?int`

**Comment by pocky** [comment]
@tristanbes wrong RFC for this case. The [https://wiki.php.net/rfc/nullable_types](https://wiki.php.net/rfc/nullable_types) do the job :)

So my answer is: I totally agree with your idea but you need to wait 7.1 :D

**Comment by GromNaN** [comment]
The purpose of [`@param`](https://www.phpdoc.org/docs/latest/references/phpdoc/tags/param.html) and [`@return`](https://www.phpdoc.org/docs/latest/references/phpdoc/tags/return.html) tags is also to support a description.

**Comment by tristanbes** [comment]
@GromNaN I'm not suggesting to remove them. I'm suggesting to not trigger a CS error when ommiting them when you have self-description-named variable with supported type hiting so we don't have redundant useless information :-)

**Comment by dbu** [comment]
seems reasonable to me. you could even complain when empty annotations without further explanation are found.
imho using param and return to further explain input and output is good practice, but when no further explanation is given, the annotations should be removed

**Comment by lucascourot** [comment]
We're currently dropping docblocks with no added value too. By the way, we switched to PHP-CS-Fixer and are using this new profile https://github.com/M6Web/php-cs-fixer-config which doesn't force you to add docblocks and which is more Symfony3 and PHP7 compliant.
