### ISSUE TITLE
Not compatible with CS 2.0+

### ISSUE THREAD

**Issue by cjunge-work** [M6Web/Symfony2-coding-standard#6]
There are issues with method signature differences beween this project and the new version of CS.

Eg:
``` PHP Strict Standards:  Declaration of Symfony2_Sniffs_Commenting_FunctionCommentSniff::processReturn() should be compatible with PEAR_Sniffs_Commenting_FunctionCommentSniff::processReturn(PHP_CodeSniffer_File $phpcsFile, $stackPtr, $commentStart)```

**Comment by cjunge-work** [comment]
If I disable error reporting I get:
```PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Class PHP_CodeSniffer_CommentParser_ClassCommentParser not found'```

**Comment by rarila** [comment]
Just hit the same problem. The cause is the [Removal of the Comment Parser](https://www.squizlabs.com/php-codesniffer/2.0.0a1-released).

Are there already plans to fix this?

**Comment by mojoLyon** [comment]
Yes we will fix this soon.

**Comment by rarila** [comment]
Oh, this is great. Thank you!
